# Generated by Django 5.0.1 on 2026-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('keywords', models.JSONField(default=list)),
                ('education', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('work_style', models.CharField(max_length=200)),
                ('skills', models.JSONField(default=list)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CareerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('keywords_detected', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('personality', models.JSONField(default=list)),
                ('matched_careers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestones', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
