# Generated by Django 5.0.1 on 2026-03-01 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedcareer',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career'),
        ),
        migrations.AddField(
            model_name='savedcareer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedcareer',
            unique_together={('user', 'career')},
        ),
    ]
