# Generated by Django 5.0.1 on 2026-04-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='roadmap_tasks',
            field=models.JSONField(default=list),
        ),
    ]
